### ISSUE TITLE
Create central economy planner

### ISSUE THREAD

**Issue by rivques** [hackclub/bag#18]
This is a database of:
- all the items
- their intended value
- the time it should take to craft/produce them
- their buy/sell prices for the general store
- probably some other stuff

The idea is that this is the single source of truth for the economy. The general store, the crafting system, and parts of the analytics will all pull data from here. 

At its core this can just be a table in a database, but here's a few nice-to-have features:
- ability to prep a new version on a staging branch and push it live w/ a button press (for easier updates of the economy)
- ablility to adjust the genstore buy/sell prices across the board as a ratio of intended price
- ability to push updates to a slack channel when changes go live e.g."Economy update: Iron now takes 30 seconds to craft (was 25), store price to buy furnaces is 14 :-gp: (was 16)"

**Comment by Bee4Queer** [comment]
I can start work on this, it would probably just be an updated version of the bag-manifest repo. Can I be assigned?

**Comment by rivques** [comment]
Go for it! Right now it's okay if it's a bit bare-bones, just make sure whatever foundation you make now can be easily extended with the features above at some point later.

**Comment by Bee4Queer** [comment]
https://github.com/hackclub/infra/issues/63

**Comment by Bee4Queer** [comment]
Also, my rough plan for this is:

1. apply for hc repo(done)
2. start with my own repo and move over to hc repo when it's approved
3. in my repo, use node js or smth to move bag-manifest to the new one and convert it to json as it's prettier and easier to use in my opinion
4. use a workflow to trigger a bag endpoint to get new data from the repo on push and update the database
5. use gh pages to publish the repo to a website so general store and bag can easily access without needing to use the github api(optional)

**Comment by rivques** [comment]
after some discussion with averse we realized that the core features of this is just the bag-manifest repo
we can build the other features on top of that repo but for now they aren't a priority
so, all parts of bag should plan to pull their data from bag-manifest
[discussion](https://hackclub.slack.com/archives/C070E6QRK1T/p1715392400941829)
