### ISSUE TITLE
Build out system for badges

### ISSUE THREAD

**Issue by rivques** [hackclub/bag#20]
Badges are non-craftable, non-tradable items that people can be granted to players for accomplishing certain tasks. Things we need to get this:

- [x] logic in Core for non-tradeable items
- [x] frontend for badge granters to grant badges to people

**Comment by Bee4Queer** [comment]
I've already started work on this in a codespace, I just need to figure out how to test it.

**Comment by Bee4Queer** [comment]
Can you assign me?
