### ISSUE TITLE
Change bag to be data-oriented

### ISSUE THREAD

**Issue by Bee4Queer** [hackclub/bag#23]
What this entails is moving most hard coded stats and information in the database to the bag-economy repo, so that it is all in one place. This will be over the course of a while, since the information is likely scattered.

**Comment by rivques** [comment]
going to close this, as it's mostly already the case, and the missing data will be added by issues like #14 (see discussion of #18 for more)

**Comment by Bee4Queer** [comment]
this should probably be closed as "not planned"
